/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wwwc.nees.joint.model;

import java.util.List;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Utility methods for the Code Generator -- upper class for each concrete class
 * generated by the compiler
 *
 * @author Olavo Holanda
 * @version 1.0 - 15/01/2012
 */
public class JOINTResource {

    protected String URI;
    protected boolean LazyLoaded;
    protected List<String> innerModifiedFields;

    public String getURI() {
        return this.URI;
    }

    public void setURI(String URI) {
        this.URI = (String) URI;
    }

    @Override
    public String toString() {
        return this.URI;
    }

    public boolean isLazyLoaded() {
        return this.LazyLoaded;
    }

    public void setLazyLoaded(boolean LazyLoaded) {
        this.LazyLoaded = (boolean) LazyLoaded;
    }

    public List<String> getInnerModifiedFields() {
        return this.innerModifiedFields;
    }

    public void setInnerModifiedFields(List<String> innerModifiedFields) {
        this.innerModifiedFields = (List<String>) innerModifiedFields;
    }
    
    @Override
    public boolean equals(Object object){
        return this.URI.equals(object.toString());
    }
    
    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 31). 
            append(this.URI).
            toHashCode();
    }
}
